exclude: 'node_modules|.git'
default_stages: [commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        files: "hrms.*"
        exclude: ".*json$|.*txt$|.*csv|.*md"
      - id: check-yaml
      - id: no-commit-to-branch
        args: ['--branch', 'develop']
      - id: check-merge-conflict
      - id: check-ast
      - id: pretty-format-json
        args: ['--no-sort-keys', '--no-ensure-ascii', '--autofix']

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear',
        ]
        args: ['--config', '.github/helper/.flake8_strict']
        exclude: ".*setup.py$"

  - repo: https://github.com/frappe/black
    rev: 951ccf4d5bb0d692b457a5ebc4215d755618eb68
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ".*setup.py$"

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false